class HTML_TAGS:
    HTML_TAG = "<html>"
    HTML_CLOSE_TAG = "</html>"
    HEAD_TAG = "<head>"
    HEAD_CLOSE_TAG = "</head>"
    TITLE_TAG = "<title>"
    TITLE_CLOSE_TAG = "</title>"
    BODY_TAG = "<body>"
    BODY_CLOSE_TAG = "</body>"
    P_TAG = "<p>"
    P_CLOSE_TAG = "</p>"
    BR_TAG = "<br/>"
    A_TAG_NEW_TAB = "<a target=\"_blank\" href=\""
    A_CLOSE_TAG = "</a>"